name: CI to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          
      - name: Build test test
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          context: Smidas
          file: Smidas/Smidas.API/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: localhost:5000/smidas-tests:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx.cache
          target: testrunner
            
      - name: Run tests
        run: docker run localhost:5000/smidas-tests:latest
      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: Smidas
          file: Smidas/Smidas.API/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smidas:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx.cache
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
